// vexp-guard - opencode / Kilo Code plugin (generated by 'vexp setup-agents'; it is
// rewritten on every setup, and a modified copy is saved to vexp-guard.js.vexp-bak
// first). Kilo v7 vendors opencode, so one plugin serves both unchanged.
//
// Blocks opencode's native grep/glob ONLY where vexp has a better answer: indexed
// source inside the workspace, while the daemon is healthy. Two deliberate limits:
//
//   1. It never touches bash. Shelling out is the escape hatch for everything vexp
//      cannot index - runtime logs, build output, files outside the repo. vexp's
//      Claude Code guard has always matched Grep|Glob|Regex only, and it works
//      precisely because that valve stays open. Blocking shell search instead
//      teaches the agent to evade (any prefix defeats it) and strands it when the
//      answer genuinely is not in the index.
//   2. It only blocks targets vexp actually indexed. A search aimed at a log file,
//      at dist/ or node_modules, or outside the workspace has no run_pipeline
//      answer, so blocking it would be a dead end rather than a redirect.
//
// Fails OPEN when the daemon is down, so native search still works with no index.
import { existsSync, readFileSync } from "node:fs";
import { join, dirname, relative, isAbsolute, sep } from "node:path";

// Walk up from start to the first ancestor that owns a .vexp dir.
function findVexpDir(start) {
  let dir = start;
  for (;;) {
    if (existsSync(join(dir, ".vexp"))) return join(dir, ".vexp");
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

// Is the pid in .vexp/daemon.pid a live process? Guards stale files left after
// a kill -9: healthy + socket can linger, so existence alone is not enough.
function pidAlive(pidFile) {
  let pid = 0;
  try { pid = parseInt(readFileSync(pidFile, "utf-8").trim(), 10); } catch (e) { return false; }
  if (!pid) return false;
  try { process.kill(pid, 0); return true; } catch (e) { return !!(e && e.code === "EPERM"); }
}

// The daemon writes .vexp/healthy when up and removes it on graceful shutdown.
// Unix: also require a live socket AND a live pid. Windows has no socket file,
// so the daemon drops a .vexp/daemon.pipe marker instead. A dead daemon fails
// open so native search still works.
function daemonHealthy(vexpDir) {
  if (!vexpDir || !existsSync(join(vexpDir, "healthy"))) return false;
  if (process.platform === "win32") return existsSync(join(vexpDir, "daemon.pipe"));
  return existsSync(join(vexpDir, "daemon.sock")) && pidAlive(join(vexpDir, "daemon.pid"));
}

const SEARCH_TOOLS = new Set(["grep", "glob"]);

// Directory names vexp never indexes: build output and vendored dependencies.
const NON_INDEXED_DIRS = [
  "node_modules", "dist", "build", "out", "coverage", "target", "vendor",
  ".vite", ".next", ".nuxt", ".output", ".turbo", ".cache", ".git", ".vexp"
];

// File kinds vexp never indexes. Logs are the case agents legitimately grep the
// most while debugging a running app. "-lock." is not redundant with ".lock":
// the two commonest JS lockfiles (package-lock.json, pnpm-lock.yaml) have no dot
// before "lock", so ".lock" alone let yarn.lock and Cargo.lock through while
// blocking them.
const NON_INDEXED_HINTS = [".log", ".lock", "-lock.", ".map", ".min.js"];

// Is this search target inside what vexp indexed? Only then is "call
// run_pipeline instead" real advice rather than a dead end. Anything that cannot
// be resolved confidently returns false (allow) - under-blocking just leaves the
// agent on grep, over-blocking strands it with no tool at all.
function isIndexedTarget(root, target) {
  if (!target) return true; // no path given: a whole-workspace search is vexp's job
  const s = String(target);
  const low = s.toLowerCase();
  for (const h of NON_INDEXED_HINTS) if (low.indexOf(h) !== -1) return false;
  let rel;
  try {
    rel = relative(root, isAbsolute(s) ? s : join(root, s));
  } catch (e) {
    return false;
  }
  if (rel === "..") return false;
  if (rel.indexOf(".." + sep) === 0) return false; // escapes the workspace
  if (isAbsolute(rel)) return false; // different root or drive
  const segs = rel.split(sep);
  for (const g of segs) if (NON_INDEXED_DIRS.indexOf(g) !== -1) return false;
  return true;
}

// Where a search is aimed. grep carries the regex in its pattern arg (never a
// path), so only path and the include filter describe its target; for glob the
// pattern IS the path.
function searchTargets(tool, args) {
  if (!args) return [];
  const out = [];
  if (args.path) out.push(args.path);
  if (tool === "glob" && args.pattern) out.push(args.pattern);
  if (tool === "grep" && args.include) out.push(args.include);
  return out;
}

export const VexpGuard = async ({ directory, worktree }) => {
  const start = worktree || directory || ".";
  let vexpDir = null;
  return {
    "tool.execute.before": async (input, output) => {
      if (!vexpDir) vexpDir = findVexpDir(start);
      if (!daemonHealthy(vexpDir)) return; // no live index -> allow
      if (!SEARCH_TOOLS.has(input.tool)) return; // bash and everything else: never blocked
      const root = dirname(vexpDir);
      const targets = searchTargets(input.tool, output && output.args);
      for (const t of targets) {
        if (!isIndexedTarget(root, t)) return; // vexp has no answer here -> allow
      }
      throw new Error(
        "vexp daemon is running. AGENT INSTRUCTION: call run_pipeline instead of " +
        input.tool + " - it returns pre-indexed, graph-ranked context in one call." +
        " This is policy, not a transient failure: do NOT work around it with shell" +
        " search or by writing a script."
      );
    },
  };
};
